### PR TITLE
fix: moving ltest to test deps from main deps

### PR DESCRIPTION
**Pull request by mpope9**
`ltest` should be a test only dep.

### CODE REVIEW

**Comment by oubiwann** [comment]
Thanks! This is a good idea -- should have done it sooner.

I've just updated the deps to use fuzzy version matching -- could you rebase and force-push your branch? I'll merge when it passes CI/CD.

**Comment by mpope9** [comment]
Yup, rebased.

**Comment by mpope9** [comment]
@oubiwann This good to go?

**Comment by oubiwann** [comment]
Oh, nice! Sorry, didn't see your update! Merging now ...

**Comment by oubiwann** [comment]
Thanks again!!!

**Pull request merged**
